## Exercises 
1\. We want to explore the `tissue_gene_expression` predictors by plotting them.  
```{r, eval=FALSE} 
data("tissue_gene_expression") 
dim(tissue_gene_expression$x) 
``` 
We want to get an idea of which observations are close to each other, but  
the predictors are 500-dimensional so plotting is difficult. Plot the first two principal components with color representing tissue type. 
2\. The predictors for each observation are measured on the same measurement device (a gene expression microarray) after an experimental procedure. A different device and procedure is used for each observation. This may introduce biases that affect all predictors for each observation in the same way. To explore the effect of this potential bias, for each observation, compute the average across all predictors and then plot this against the first PC with color representing tissue. Report the correlation. 
3\. We see an association with the first PC and the observation averages. Redo the PCA but only after removing the center. 
4\. For the first 10 PCs, make a boxplot showing the values for each tissue.  
5\. Plot the percent variance explained by PC number. Hint: use the `summary` function. 

 
