## Random Variales Exercises


1\. In American Roulette you can also bet on green. There are 18 reds, 18 blacks and 2 greens (0 and 00). What are the chances the green comes out?


2\. The payout for winning on green is \$17 dollars. This means that if you bet a dollar and it lands on green, you get \$17. Create a sampling model using sample to simulate the random variable $X$ for your winnings. Hint: see the example below for how it should look like when betting on red.

```{r}
x <- sample(c(1,-1), 1, prob = c(9/19, 10/19))
```

3\. Compute the expected value of $X$.


4\. Compute the standard error of $X$.

    
5\. Now create a random variable $S$ that is the sum of your winnings after betting on green 1000 times. Hint: change the argument `size` and `replace` in your answer to question 2. Start your code by setting the seed to 1 with `set.seed(1)`.

6\. What is the expected value of $S$?


7\. What is the standard error of $S$?


8\. What is the probability that you end up winning money? Hint: use the CLT.


9\. Create a Monte Carlo simulation that generates 1,000 outcomes of $S$. Compute the average and standard deviation of the resulting list to confirm the results of 6 and 7. Start your code by setting the seed to 1 with `set.seed(1)`.




10\. Now check your answer to 8 using the Monte Carlo result. 

11\. The Monte Carlo result and the CLT approximation are close, but not that close. What could account for this?

a. 1,000 simulations is not enough. If we do more, they match.
b. The CLT does not work as well when the probability of success is small. In this case, it was 1/19. If we make the number of roulette plays bigger, they will match better.
c. The difference is within rounding error.
d. The CLT only works for averages.


12\. Now create a random variable $Y$ that is your average winnings per bet after playing off your winnings after betting on green 1,000 times.

13\. What is the expected value of $Y$?

14\. What is the standard error of $Y$?

15\. What is the probability that you end up with winnings per game that are positive? Hint: use the CLT.


16\. Create a Monte Carlo simulation that generates 2,500 outcomes of $Y$. Compute the average and standard deviation of the resulting list to confirm the results of 6 and 7. Start your code by setting the seed to 1 with `set.seed(1)`.

17\. Now check your answer to 8 using the Monte Carlo result. 

18\. The Monte Carlo result and the CLT approximation are now much closer.  What could account for this?

a. We are now computing averages instead of sums.
b. 2,500 Monte Carlo simulations is not better than 1,000.
c. The CLT works better when the sample size is larger. We increased from 1,000 to 2,500.
d. It is not closer. The difference is within rounding error.

